# Generated by Django 4.2.7 on 2023-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_audio_title', models.TextField(blank=True)),
                ('database_audio_number', models.IntegerField(blank=True)),
                ('database_audio_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_image_title', models.TextField(blank=True)),
                ('database_image_number', models.IntegerField(blank=True)),
                ('database_image_content', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_text_title', models.TextField(blank=True)),
                ('database_text_number', models.IntegerField(blank=True)),
                ('database_text_content', models.TextField(blank=True)),
            ],
        ),
    ]
